export const expressSyllabus = {
  title: "Express.js",
  sections: [
    {
      title: "Basics",
      icon: "🚂",
      description: "Get started with Express.js – understand the framework, setup, routing, middleware, and handling requests/responses.",
      topics: [
        { title: "What is Express.js?", slug: "what-is-express", icon: "🚂", iconBgClassName: "bg-gray-100" },
        { title: "Setting Up Express (Installation, Hello World)", slug: "setup", icon: "⚙️", iconBgClassName: "bg-blue-100" },
        { title: "Application Object (app.get, app.post, etc.)", slug: "app-object", icon: "📱", iconBgClassName: "bg-green-100" },
        { title: "Basic Routing (GET, POST, PUT, DELETE)", slug: "basic-routing", icon: "🧭", iconBgClassName: "bg-yellow-100" },
        { title: "Route Parameters & Query Strings", slug: "route-params", icon: "🔢", iconBgClassName: "bg-purple-100" },
        { title: "Request Object (req.params, req.query, req.body)", slug: "request-object", icon: "📥", iconBgClassName: "bg-pink-100" },
        { title: "Response Object (res.send, res.json, res.status)", slug: "response-object", icon: "📤", iconBgClassName: "bg-orange-100" },
        { title: "Middleware (Introduction)", slug: "middleware-intro", icon: "⛓️", iconBgClassName: "bg-indigo-100" },
        { title: "Built-in Middleware (express.json, express.static)", slug: "builtin-middleware", icon: "🔧", iconBgClassName: "bg-cyan-100" },
        { title: "Error Handling Middleware", slug: "error-middleware", icon: "⚠️", iconBgClassName: "bg-red-100" },
      ],
    },
    {
      title: "Intermediate",
      icon: "🟠",
      description: "Deepen Express knowledge – advanced routing, template engines, file uploads, sessions, cookies, authentication, and database integration.",
      topics: [
        { title: "Route Handlers & Route Chaining", slug: "route-handlers", icon: "🔗", iconBgClassName: "bg-blue-100" },
        { title: "Express Router (Modular Routes)", slug: "express-router", icon: "📁", iconBgClassName: "bg-green-100" },
        { title: "Template Engines (EJS, Pug, Handlebars)", slug: "template-engines", icon: "📄", iconBgClassName: "bg-purple-100" },
        { title: "Serving Static Files", slug: "static-files", icon: "📁", iconBgClassName: "bg-yellow-100" },
        { title: "File Uploads (multer)", slug: "file-uploads", icon: "📎", iconBgClassName: "bg-pink-100" },
        { title: "Sessions & Cookies", slug: "sessions-cookies", icon: "🍪", iconBgClassName: "bg-orange-100" },
        { title: "Authentication (JWT, Passport.js)", slug: "authentication", icon: "🔐", iconBgClassName: "bg-indigo-100" },
        { title: "Password Hashing (bcrypt)", slug: "hashing", icon: "🔒", iconBgClassName: "bg-cyan-100" },
        { title: "Database Integration (MongoDB with Mongoose)", slug: "mongodb-integration", icon: "🍃", iconBgClassName: "bg-green-200" },
        { title: "Database Integration (PostgreSQL with Sequelize)", slug: "postgres-integration", icon: "🐘", iconBgClassName: "bg-blue-200" },
        { title: "Environment Variables (dotenv)", slug: "env-vars", icon: "🔐", iconBgClassName: "bg-red-100" },
        { title: "CORS (Cross-Origin Resource Sharing)", slug: "cors", icon: "🌐", iconBgClassName: "bg-teal-100" },
        { title: "Compression (express compression)", slug: "compression", icon: "🗜️", iconBgClassName: "bg-lime-100" },
        { title: "Logging (morgan, winston)", slug: "logging", icon: "📝", iconBgClassName: "bg-gray-100" },
      ],
    },
    {
      title: "Advanced",
      icon: "🔴",
      description: "Master advanced Express – security best practices, performance optimization, testing, WebSockets, GraphQL, microservices, and deployment.",
      topics: [
        { title: "Security Best Practices (Helmet, Rate Limiting)", slug: "security", icon: "🛡️", iconBgClassName: "bg-blue-100" },
        { title: "Preventing XSS & CSRF", slug: "xss-csrf", icon: "⚠️", iconBgClassName: "bg-red-100" },
        { title: "Input Validation & Sanitization (express-validator)", slug: "validation", icon: "✅", iconBgClassName: "bg-green-100" },
        { title: "Performance Optimization (Caching, Clustering)", slug: "performance", icon: "⚡", iconBgClassName: "bg-yellow-100" },
        { title: "Rate Limiting & Throttling", slug: "rate-limiting", icon: "🐌", iconBgClassName: "bg-purple-100" },
        { title: "Testing (Jest, Supertest)", slug: "testing", icon: "🧪", iconBgClassName: "bg-pink-100" },
        { title: "WebSockets (Socket.io with Express)", slug: "websockets", icon: "🔌", iconBgClassName: "bg-orange-100" },
        { title: "GraphQL with Apollo Server Express", slug: "graphql", icon: "📊", iconBgClassName: "bg-indigo-100" },
        { title: "Microservices Architecture with Express", slug: "microservices", icon: "🔧", iconBgClassName: "bg-cyan-100" },
        { title: "API Documentation (Swagger/OpenAPI)", slug: "api-docs", icon: "📖", iconBgClassName: "bg-teal-100" },
        { title: "Dockerizing Express Apps", slug: "docker", icon: "🐳", iconBgClassName: "bg-blue-200" },
        { title: "Deployment (Heroku, Vercel, AWS, PM2)", slug: "deployment", icon: "🚀", iconBgClassName: "bg-gray-100" },
        { title: "TypeScript with Express (ts-node, types)", slug: "typescript-express", icon: "📘", iconBgClassName: "bg-blue-300" },
        { title: "Load Balancing & Reverse Proxy (Nginx)", slug: "load-balancing", icon: "⚖️", iconBgClassName: "bg-green-300" },
        { title: "Monitoring & Logging (New Relic, Winston)", slug: "monitoring", icon: "📈", iconBgClassName: "bg-purple-300" },
        { title: "CI/CD Pipelines (GitHub Actions)", slug: "cicd", icon: "🔄", iconBgClassName: "bg-yellow-200" },
      ],
    },
  ],
};