// javascript.ts (or in your main registry)
export const javascriptSyllabus = {
  title: "JavaScript",
  sections: [
    {
      title: "Basics",
      icon: "🧱",
      description: "Learn the core building blocks of JavaScript – syntax, variables, data types, operators, control flow, and basic functions.",
      topics: [
        { title: "What is JavaScript?", slug: "what-is-javascript", icon: "🌐", iconBgClassName: "bg-gray-100" },
        { title: "Writing JavaScript", slug: "writing-js", icon: "✍️", iconBgClassName: "bg-gray-100" },
        { title: "Console & Debugging", slug: "console", icon: "🖥️", iconBgClassName: "bg-gray-100" },
        { title: "Variables (var, let, const)", slug: "variables", icon: "📦", iconBgClassName: "bg-yellow-100" },
        { title: "Data Types", slug: "data-types", icon: "🔢", iconBgClassName: "bg-blue-100" },
        { title: "Operators", slug: "operators", icon: "➕", iconBgClassName: "bg-green-100" },
        { title: "Control Flow (if, else, switch)", slug: "control-flow", icon: "🔀", iconBgClassName: "bg-purple-100" },
        { title: "Loops (for, while, do...while)", slug: "loops", icon: "🔄", iconBgClassName: "bg-indigo-100" },
        { title: "Functions (Basics)", slug: "functions-basics", icon: "⚙️", iconBgClassName: "bg-pink-100" },
        { title: "Arrays & Objects Basics", slug: "arrays-objects-basics", icon: "🗂️", iconBgClassName: "bg-orange-100" },
        { title: "DOM Basics", slug: "dom-basics", icon: "🌳", iconBgClassName: "bg-emerald-100" },
      ],
    },
    {
      title: "Intermediate",
      icon: "⚡",
      description: "Dive deeper into JavaScript – scope, closures, advanced functions, error handling, ES6+ features, asynchronous JS, and more.",
      topics: [
        { title: "Scope (Global, Local, Block)", slug: "scope", icon: "🎯", iconBgClassName: "bg-red-100" },
        { title: "Closures", slug: "closures", icon: "🔒", iconBgClassName: "bg-red-100" },
        { title: "Advanced Functions", slug: "advanced-functions", icon: "⚡", iconBgClassName: "bg-purple-100" },
        { title: "Error Handling (try...catch)", slug: "error-handling", icon: "⚠️", iconBgClassName: "bg-yellow-100" },
        { title: "ES6+ Features", slug: "es6-features", icon: "✨", iconBgClassName: "bg-indigo-100" },
        { title: "Destructuring & Spread/Rest", slug: "destructuring-spread-rest", icon: "📦", iconBgClassName: "bg-blue-100" },
        { title: "Asynchronous JS (Callbacks)", slug: "async-callbacks", icon: "⏰", iconBgClassName: "bg-teal-100" },
        { title: "Promises", slug: "promises", icon: "🤝", iconBgClassName: "bg-teal-100" },
        { title: "Async/Await", slug: "async-await", icon: "⏳", iconBgClassName: "bg-indigo-100" },
        { title: "Advanced DOM Manipulation", slug: "dom-advanced", icon: "🌲", iconBgClassName: "bg-emerald-100" },
        { title: "Browser APIs (Storage, Fetch)", slug: "browser-apis", icon: "🌐", iconBgClassName: "bg-gray-100" },
      ],
    },
    {
      title: "Advanced",
      icon: "🚀",
      description: "Master JavaScript internals, performance, design patterns, testing, security, and real-world API integration.",
      topics: [
        { title: "Execution Context & Hoisting", slug: "execution-context-hoisting", icon: "🧠", iconBgClassName: "bg-rose-100" },
        { title: "Prototypes & Inheritance", slug: "prototypes-inheritance", icon: "🧬", iconBgClassName: "bg-fuchsia-100" },
        { title: "ES6 Classes", slug: "classes", icon: "🏛️", iconBgClassName: "bg-violet-100" },
        { title: "Modules (ES Modules)", slug: "modules", icon: "📦", iconBgClassName: "bg-blue-100" },
        { title: "Event Loop & Concurrency", slug: "event-loop", icon: "🔄", iconBgClassName: "bg-cyan-100" },
        { title: "Performance Optimization", slug: "performance-optimization", icon: "⚡", iconBgClassName: "bg-lime-100" },
        { title: "Design Patterns", slug: "design-patterns", icon: "🏗️", iconBgClassName: "bg-amber-100" },
        { title: "Testing & Debugging", slug: "testing-debugging", icon: "🧪", iconBgClassName: "bg-slate-100" },
        { title: "Security & Best Practices", slug: "security-best-practices", icon: "🔐", iconBgClassName: "bg-red-100" },
        { title: "Working with APIs", slug: "working-with-apis", icon: "🔌", iconBgClassName: "bg-green-100" },
      ],
    },
  ],
};