export const mongodbSyllabus = {
  title: "MongoDB",
  sections: [
    {
      title: "Basics",
      icon: "🍃",
      description: "Get started with MongoDB – understand NoSQL concepts, installation, CRUD operations, and basic querying.",
      topics: [
        { title: "What is MongoDB? (NoSQL vs SQL)", slug: "what-is-mongodb", icon: "🍃", iconBgClassName: "bg-green-100" },
        { title: "Installing MongoDB (Community Edition, Atlas)", slug: "installation", icon: "📦", iconBgClassName: "bg-gray-100" },
        { title: "MongoDB Shell (mongosh)", slug: "mongosh", icon: "🖥️", iconBgClassName: "bg-blue-100" },
        { title: "Databases, Collections & Documents", slug: "databases-collections", icon: "🗄️", iconBgClassName: "bg-purple-100" },
        { title: "CRUD Operations (Create, Read, Update, Delete)", slug: "crud", icon: "📝", iconBgClassName: "bg-yellow-100" },
        { title: "Insert Documents (insertOne, insertMany)", slug: "insert", icon: "➕", iconBgClassName: "bg-green-100" },
        { title: "Query Documents (find, findOne, pretty)", slug: "query", icon: "🔍", iconBgClassName: "bg-indigo-100" },
        { title: "Update Documents (updateOne, updateMany, replaceOne)", slug: "update", icon: "✏️", iconBgClassName: "bg-orange-100" },
        { title: "Delete Documents (deleteOne, deleteMany)", slug: "delete", icon: "🗑️", iconBgClassName: "bg-red-100" },
        { title: "Projection & Sorting", slug: "projection-sort", icon: "📊", iconBgClassName: "bg-pink-100" },
        { title: "Limiting & Skipping Results", slug: "limit-skip", icon: "⏭️", iconBgClassName: "bg-cyan-100" },
      ],
    },
    {
      title: "Intermediate",
      icon: "🟡",
      description: "Deepen MongoDB knowledge – query operators, indexing, aggregation pipeline, relationships, and data modeling.",
      topics: [
        { title: "Comparison Operators ($eq, $gt, $lt, $in, etc.)", slug: "comparison-operators", icon: "⚖️", iconBgClassName: "bg-blue-100" },
        { title: "Logical Operators ($and, $or, $not, $nor)", slug: "logical-operators", icon: "🔀", iconBgClassName: "bg-green-100" },
        { title: "Element Operators ($exists, $type)", slug: "element-operators", icon: "🔍", iconBgClassName: "bg-purple-100" },
        { title: "Array Operators ($in, $all, $size, $elemMatch)", slug: "array-operators", icon: "🗂️", iconBgClassName: "bg-yellow-100" },
        { title: "Regular Expressions ($regex)", slug: "regex", icon: "🔤", iconBgClassName: "bg-pink-100" },
        { title: "Indexing (Single, Compound, Multikey)", slug: "indexing", icon: "📇", iconBgClassName: "bg-orange-100" },
        { title: "Aggregation Pipeline (Introduction)", slug: "aggregation-intro", icon: "🔗", iconBgClassName: "bg-indigo-100" },
        { title: "Aggregation Stages ($match, $group, $sort, $project)", slug: "aggregation-stages", icon: "⚙️", iconBgClassName: "bg-cyan-100" },
        { title: "Aggregation Operators ($sum, $avg, $push, $addToSet)", slug: "aggregation-operators", icon: "➕", iconBgClassName: "bg-teal-100" },
        { title: "$lookup (Joining Collections)", slug: "lookup", icon: "🔗", iconBgClassName: "bg-red-100" },
        { title: "$unwind (Working with Arrays)", slug: "unwind", icon: "🌀", iconBgClassName: "bg-lime-100" },
        { title: "Data Modeling (Embedding vs Referencing)", slug: "data-modeling", icon: "🏗️", iconBgClassName: "bg-amber-100" },
        { title: "Relationships (One-to-One, One-to-Many, Many-to-Many)", slug: "relationships", icon: "🔗", iconBgClassName: "bg-purple-200" },
        { title: "Transactions (ACID Compliance)", slug: "transactions", icon: "💸", iconBgClassName: "bg-blue-200" },
      ],
    },
    {
      title: "Advanced",
      icon: "🔴",
      description: "Master advanced MongoDB – replication, sharding, performance optimization, security, backup strategies, and integration with applications.",
      topics: [
        { title: "Replication (Replica Sets)", slug: "replication", icon: "🔄", iconBgClassName: "bg-blue-100" },
        { title: "Sharding (Horizontal Scaling)", slug: "sharding", icon: "🔪", iconBgClassName: "bg-green-100" },
        { title: "Shard Keys & Chunks", slug: "shard-keys", icon: "🔑", iconBgClassName: "bg-purple-100" },
        { title: "High Availability & Failover", slug: "high-availability", icon: "🛡️", iconBgClassName: "bg-yellow-100" },
        { title: "Performance Optimization (Query Profiling, Explain)", slug: "performance", icon: "⚡", iconBgClassName: "bg-pink-100" },
        { title: "Indexing Strategies & Optimization", slug: "index-optimization", icon: "📊", iconBgClassName: "bg-orange-100" },
        { title: "Change Streams (Real-time Data)", slug: "change-streams", icon: "📡", iconBgClassName: "bg-indigo-100" },
        { title: "MongoDB Security (Authentication, Authorization, TLS)", slug: "security", icon: "🔐", iconBgClassName: "bg-red-100" },
        { title: "Backup & Restore Strategies (mongodump, mongorestore)", slug: "backup", icon: "💾", iconBgClassName: "bg-teal-100" },
        { title: "MongoDB Atlas (Cloud Database)", slug: "atlas", icon: "☁️", iconBgClassName: "bg-cyan-100" },
        { title: "MongoDB Compass (GUI Tool)", slug: "compass", icon: "🧭", iconBgClassName: "bg-lime-100" },
        { title: "MongoDB with Node.js (Mongoose)", slug: "mongoose", icon: "🟢", iconBgClassName: "bg-green-200" },
        { title: "MongoDB with Python (PyMongo)", slug: "pymongo", icon: "🐍", iconBgClassName: "bg-blue-200" },
        { title: "Aggregation Pipeline Optimization", slug: "agg-optimization", icon: "⚙️", iconBgClassName: "bg-purple-200" },
        { title: "Multi-Document ACID Transactions", slug: "acid-transactions", icon: "💸", iconBgClassName: "bg-yellow-200" },
        { title: "Monitoring & Alerting (Atlas, Ops Manager)", slug: "monitoring", icon: "📈", iconBgClassName: "bg-red-200" },
        { title: "MongoDB Stitch (Serverless Platform)", slug: "stitch", icon: "🔗", iconBgClassName: "bg-orange-200" },
        { title: "Migrations & Schema Versioning", slug: "migrations", icon: "🔄", iconBgClassName: "bg-indigo-200" },
      ],
    },
  ],
};