export const nextjsSyllabus = {
  title: "Next.js",
  sections: [
    {
      title: "Basics",
      icon: "🔵",
      description: "Get started with Next.js – understand the framework, routing, pages, links, assets, and styling.",
      topics: [
        { title: "What is Next.js?", slug: "what-is-nextjs", icon: "▲", iconBgClassName: "bg-black-100 text-black" },
        { title: "Setting Up a Next.js App", slug: "setup", icon: "⚙️", iconBgClassName: "bg-gray-100" },
        { title: "Pages & File-based Routing", slug: "pages-routing", icon: "📄", iconBgClassName: "bg-blue-100" },
        { title: "Linking Between Pages (Link component)", slug: "linking", icon: "🔗", iconBgClassName: "bg-green-100" },
        { title: "Static Assets (Images, Fonts)", slug: "assets", icon: "🖼️", iconBgClassName: "bg-purple-100" },
        { title: "Styling (CSS Modules, Tailwind, Global CSS)", slug: "styling", icon: "🎨", iconBgClassName: "bg-pink-100" },
        { title: "Layouts & Components", slug: "layouts", icon: "🏗️", iconBgClassName: "bg-orange-100" },
        { title: "Environment Variables", slug: "env-vars", icon: "🔐", iconBgClassName: "bg-yellow-100" },
      ],
    },
    {
      title: "Intermediate",
      icon: "🟠",
      description: "Master data fetching, API routes, dynamic routing, middleware, and key optimizations.",
      topics: [
        { title: "Data Fetching (SSR, SSG, CSR)", slug: "data-fetching", icon: "📡", iconBgClassName: "bg-blue-100" },
        { title: "getStaticProps & getStaticPaths", slug: "getstaticprops", icon: "📦", iconBgClassName: "bg-green-100" },
        { title: "getServerSideProps", slug: "getserversideprops", icon: "🖥️", iconBgClassName: "bg-purple-100" },
        { title: "Client-side Data Fetching (SWR, React Query)", slug: "client-fetching", icon: "🔄", iconBgClassName: "bg-pink-100" },
        { title: "API Routes", slug: "api-routes", icon: "🔌", iconBgClassName: "bg-orange-100" },
        { title: "Dynamic Routes", slug: "dynamic-routes", icon: "🔀", iconBgClassName: "bg-yellow-100" },
        { title: "Catch-all & Optional Catch-all Routes", slug: "catch-all-routes", icon: "🌐", iconBgClassName: "bg-indigo-100" },
        { title: "Middleware", slug: "middleware", icon: "⛓️", iconBgClassName: "bg-red-100" },
        { title: "Image Optimization (next/image)", slug: "image-optimization", icon: "🖼️", iconBgClassName: "bg-teal-100" },
        { title: "Font Optimization (next/font)", slug: "font-optimization", icon: "🔤", iconBgClassName: "bg-cyan-100" },
        { title: "SEO with next/head", slug: "seo", icon: "🔍", iconBgClassName: "bg-lime-100" },
      ],
    },
    {
      title: "Advanced",
      icon: "🔴",
      description: "Deep dive into App Router, advanced rendering patterns, ISR, performance, authentication, deployment, and production best practices.",
      topics: [
        { title: "App Router (Next.js 13+)", slug: "app-router", icon: "📱", iconBgClassName: "bg-blue-100" },
        { title: "Server Components vs Client Components", slug: "server-components", icon: "🖥️", iconBgClassName: "bg-green-100" },
        { title: "Incremental Static Regeneration (ISR)", slug: "isr", icon: "🔄", iconBgClassName: "bg-purple-100" },
        { title: "Edge Runtime & Edge Config", slug: "edge-runtime", icon: "⚡", iconBgClassName: "bg-yellow-100" },
        { title: "Authentication (NextAuth.js, JWT)", slug: "authentication", icon: "🔐", iconBgClassName: "bg-red-100" },
        { title: "Middleware for Auth & Redirects", slug: "middleware-auth", icon: "⛓️", iconBgClassName: "bg-orange-100" },
        { title: "Internationalization (i18n)", slug: "i18n", icon: "🌍", iconBgClassName: "bg-indigo-100" },
        { title: "Performance Optimization (Bundle Analysis)", slug: "performance", icon: "⚡", iconBgClassName: "bg-cyan-100" },
        { title: "Static Export (next export)", slug: "static-export", icon: "📦", iconBgClassName: "bg-gray-100" },
        { title: "Deployment (Vercel, Docker, Self-hosted)", slug: "deployment", icon: "🚀", iconBgClassName: "bg-black-100" },
        { title: "Testing (Jest, React Testing Library, Cypress)", slug: "testing", icon: "🧪", iconBgClassName: "bg-pink-100" },
        { title: "Custom Server (Express, Fastify)", slug: "custom-server", icon: "🖧", iconBgClassName: "bg-teal-100" },
        { title: "Security Best Practices", slug: "security", icon: "🛡️", iconBgClassName: "bg-red-100" },
        { title: "Monorepos & Turbopack", slug: "monorepo-turbopack", icon: "🧩", iconBgClassName: "bg-lime-100" },
      ],
    },
  ],
};