export const nodejsSyllabus = {
  title: "Node.js",
  sections: [
    {
      title: "Basics",
      icon: "🟢",
      description: "Get started with Node.js – understand the runtime, modules, file system, NPM, and basic server creation.",
      topics: [
        { title: "What is Node.js?", slug: "what-is-nodejs", icon: "🟢", iconBgClassName: "bg-green-100" },
        { title: "Installing Node.js & NPM", slug: "installation", icon: "📦", iconBgClassName: "bg-gray-100" },
        { title: "Running JavaScript with Node", slug: "running-js", icon: "▶️", iconBgClassName: "bg-blue-100" },
        { title: "Global Objects (global, process)", slug: "global-objects", icon: "🌍", iconBgClassName: "bg-purple-100" },
        { title: "Modules (CommonJS, require, module.exports)", slug: "modules", icon: "📦", iconBgClassName: "bg-yellow-100" },
        { title: "NPM & Package Management", slug: "npm", icon: "📚", iconBgClassName: "bg-red-100" },
        { title: "File System (fs module)", slug: "file-system", icon: "📁", iconBgClassName: "bg-orange-100" },
        { title: "Path Module", slug: "path-module", icon: "🛤️", iconBgClassName: "bg-indigo-100" },
        { title: "OS Module", slug: "os-module", icon: "💻", iconBgClassName: "bg-pink-100" },
        { title: "Creating a Simple HTTP Server", slug: "http-server", icon: "🌐", iconBgClassName: "bg-teal-100" },
      ],
    },
    {
      title: "Intermediate",
      icon: "🟡",
      description: "Deepen Node.js knowledge – events, streams, buffers, Express.js, middleware, database integration, and authentication.",
      topics: [
        { title: "Event Emitter & Event Loop", slug: "event-emitter", icon: "📡", iconBgClassName: "bg-blue-100" },
        { title: "Buffers & Streams", slug: "buffers-streams", icon: "🌊", iconBgClassName: "bg-cyan-100" },
        { title: "Pipes & Pipe Chaining", slug: "pipes", icon: "🔗", iconBgClassName: "bg-green-100" },
        { title: "Express.js Framework", slug: "express", icon: "🚂", iconBgClassName: "bg-gray-100" },
        { title: "Routing in Express", slug: "express-routing", icon: "🧭", iconBgClassName: "bg-purple-100" },
        { title: "Middleware", slug: "middleware", icon: "⛓️", iconBgClassName: "bg-yellow-100" },
        { title: "Error Handling", slug: "error-handling", icon: "⚠️", iconBgClassName: "bg-red-100" },
        { title: "Environment Variables (dotenv)", slug: "env-vars", icon: "🔐", iconBgClassName: "bg-orange-100" },
        { title: "Database Integration (MongoDB, PostgreSQL)", slug: "database", icon: "🗄️", iconBgClassName: "bg-indigo-100" },
        { title: "Authentication (JWT, Sessions)", slug: "authentication", icon: "🔑", iconBgClassName: "bg-pink-100" },
        { title: "Password Hashing (bcrypt)", slug: "hashing", icon: "🔒", iconBgClassName: "bg-teal-100" },
        { title: "REST API Development", slug: "rest-api", icon: "📡", iconBgClassName: "bg-lime-100" },
        { title: "Working with Child Processes", slug: "child-process", icon: "👶", iconBgClassName: "bg-amber-100" },
      ],
    },
    {
      title: "Advanced",
      icon: "🔴",
      description: "Master advanced Node.js concepts – clustering, worker threads, GraphQL, microservices, security, testing, deployment, and performance optimization.",
      topics: [
        { title: "Cluster Module & Load Balancing", slug: "cluster", icon: "⚖️", iconBgClassName: "bg-blue-100" },
        { title: "Worker Threads", slug: "worker-threads", icon: "🧵", iconBgClassName: "bg-green-100" },
        { title: "GraphQL with Apollo/Express", slug: "graphql", icon: "📊", iconBgClassName: "bg-purple-100" },
        { title: "WebSockets (Socket.io)", slug: "websockets", icon: "🔌", iconBgClassName: "bg-yellow-100" },
        { title: "Microservices Architecture", slug: "microservices", icon: "🔧", iconBgClassName: "bg-red-100" },
        { title: "Message Queues (RabbitMQ, Redis)", slug: "message-queues", icon: "📨", iconBgClassName: "bg-orange-100" },
        { title: "Security Best Practices (Helmet, CORS, XSS)", slug: "security", icon: "🛡️", iconBgClassName: "bg-indigo-100" },
        { title: "Rate Limiting & Request Throttling", slug: "rate-limiting", icon: "🐌", iconBgClassName: "bg-pink-100" },
        { title: "Logging (Winston, Morgan)", slug: "logging", icon: "📝", iconBgClassName: "bg-teal-100" },
        { title: "Testing (Jest, Mocha, Chai, Supertest)", slug: "testing", icon: "🧪", iconBgClassName: "bg-cyan-100" },
        { title: "Debugging Node.js Applications", slug: "debugging", icon: "🐛", iconBgClassName: "bg-lime-100" },
        { title: "Performance Optimization (Profiling, Caching)", slug: "performance", icon: "⚡", iconBgClassName: "bg-amber-100" },
        { title: "Dockerizing Node.js Apps", slug: "docker", icon: "🐳", iconBgClassName: "bg-blue-200" },
        { title: "Deployment (PM2, Nginx, Vercel, AWS)", slug: "deployment", icon: "🚀", iconBgClassName: "bg-gray-100" },
        { title: "Monitoring & Logging (New Relic, Datadog)", slug: "monitoring", icon: "📊", iconBgClassName: "bg-purple-200" },
        { title: "TypeScript with Node.js", slug: "typescript-node", icon: "📘", iconBgClassName: "bg-blue-100" },
        { title: "Building CLI Tools with Node", slug: "cli-tools", icon: "⌨️", iconBgClassName: "bg-gray-200" },
      ],
    },
  ],
};