export const pythonSyllabus = {
  title: "Python",
  sections: [
    {
      title: "Basics",
      icon: "🐍",
      description: "Get started with Python – understand syntax, variables, data types, control flow, functions, and basic data structures.",
      topics: [
        { title: "What is Python?", slug: "what-is-python", icon: "🐍", iconBgClassName: "bg-green-100" },
        { title: "Setting Up Python (Installation, IDE, REPL)", slug: "setup", icon: "⚙️", iconBgClassName: "bg-gray-100" },
        { title: "Variables & Data Types (int, float, str, bool)", slug: "variables-types", icon: "📦", iconBgClassName: "bg-blue-100" },
        { title: "Basic Operators (Arithmetic, Comparison, Logical)", slug: "operators", icon: "➕", iconBgClassName: "bg-yellow-100" },
        { title: "Strings & String Methods", slug: "strings", icon: "🔤", iconBgClassName: "bg-purple-100" },
        { title: "Lists & Tuples", slug: "lists-tuples", icon: "📋", iconBgClassName: "bg-pink-100" },
        { title: "Dictionaries & Sets", slug: "dicts-sets", icon: "📖", iconBgClassName: "bg-orange-100" },
        { title: "Control Flow (if, elif, else)", slug: "control-flow", icon: "🔀", iconBgClassName: "bg-indigo-100" },
        { title: "Loops (for, while, break, continue)", slug: "loops", icon: "🔄", iconBgClassName: "bg-cyan-100" },
        { title: "Functions (def, parameters, return)", slug: "functions", icon: "⚙️", iconBgClassName: "bg-red-100" },
        { title: "Scope (global, local, nonlocal)", slug: "scope", icon: "🎯", iconBgClassName: "bg-teal-100" },
        { title: "Input/Output (print, input, file reading)", slug: "io", icon: "📥", iconBgClassName: "bg-lime-100" },
      ],
    },
    {
      title: "Intermediate",
      icon: "🟡",
      description: "Deepen Python knowledge – modules, packages, error handling, OOP, decorators, iterators, generators, and working with files/APIs.",
      topics: [
        { title: "Modules & Packages (import, __name__)", slug: "modules-packages", icon: "📦", iconBgClassName: "bg-blue-100" },
        { title: "Error & Exception Handling (try, except, finally)", slug: "error-handling", icon: "⚠️", iconBgClassName: "bg-red-100" },
        { title: "Object-Oriented Programming (Classes, Objects)", slug: "oop-basics", icon: "🏛️", iconBgClassName: "bg-purple-100" },
        { title: "Inheritance, Polymorphism, Encapsulation", slug: "oop-advanced", icon: "🧬", iconBgClassName: "bg-pink-100" },
        { title: "Magic Methods (__init__, __str__, __repr__)", slug: "magic-methods", icon: "✨", iconBgClassName: "bg-yellow-100" },
        { title: "Decorators", slug: "decorators", icon: "🎨", iconBgClassName: "bg-green-100" },
        { title: "Iterators & Iterables", slug: "iterators", icon: "🔄", iconBgClassName: "bg-orange-100" },
        { title: "Generators (yield)", slug: "generators", icon: "⚙️", iconBgClassName: "bg-teal-100" },
        { title: "Lambda Functions & map, filter, reduce", slug: "lambda", icon: "λ", iconBgClassName: "bg-indigo-100" },
        { title: "List Comprehensions & Dict Comprehensions", slug: "comprehensions", icon: "📝", iconBgClassName: "bg-cyan-100" },
        { title: "Working with Files (open, read, write, csv, json)", slug: "file-handling", icon: "📄", iconBgClassName: "bg-gray-100" },
        { title: "Working with APIs (requests module)", slug: "apis", icon: "🌐", iconBgClassName: "bg-blue-200" },
        { title: "Virtual Environments (venv, pip)", slug: "virtual-env", icon: "📦", iconBgClassName: "bg-purple-200" },
        { title: "Testing (unittest, pytest basics)", slug: "testing", icon: "🧪", iconBgClassName: "bg-red-200" },
      ],
    },
    {
      title: "Advanced",
      icon: "🔴",
      description: "Master advanced Python – concurrency, decorators deeper, context managers, metaprogramming, design patterns, performance, and popular frameworks.",
      topics: [
        { title: "Concurrency (threading, multiprocessing)", slug: "concurrency", icon: "🧵", iconBgClassName: "bg-blue-100" },
        { title: "Asyncio (async/await, event loop)", slug: "asyncio", icon: "⏳", iconBgClassName: "bg-green-100" },
        { title: "Advanced Decorators (with arguments, classes)", slug: "advanced-decorators", icon: "🎭", iconBgClassName: "bg-purple-100" },
        { title: "Context Managers (with statement, __enter__/__exit__)", slug: "context-managers", icon: "📂", iconBgClassName: "bg-yellow-100" },
        { title: "Metaclasses", slug: "metaclasses", icon: "🧠", iconBgClassName: "bg-pink-100" },
        { title: "Descriptors & Properties", slug: "descriptors", icon: "🔧", iconBgClassName: "bg-orange-100" },
        { title: "Design Patterns in Python", slug: "design-patterns", icon: "🏗️", iconBgClassName: "bg-indigo-100" },
        { title: "Type Hints & Annotations (mypy)", slug: "type-hints", icon: "📝", iconBgClassName: "bg-cyan-100" },
        { title: "Performance Optimization (cProfile, timeit)", slug: "performance", icon: "⚡", iconBgClassName: "bg-red-100" },
        { title: "C Extensions (ctypes, Cython)", slug: "c-extensions", icon: "🔌", iconBgClassName: "bg-teal-100" },
        { title: "Web Frameworks (Flask, Django basics)", slug: "web-frameworks", icon: "🌐", iconBgClassName: "bg-blue-200" },
        { title: "Data Science & NumPy/Pandas intro", slug: "data-science", icon: "📊", iconBgClassName: "bg-green-200" },
        { title: "Packaging & Distribution (PyPI, setup.py)", slug: "packaging", icon: "📦", iconBgClassName: "bg-purple-200" },
        { title: "Logging & Debugging (logging module, pdb)", slug: "logging-debugging", icon: "🐛", iconBgClassName: "bg-yellow-200" },
        { title: "Security Best Practices", slug: "security", icon: "🔐", iconBgClassName: "bg-red-200" },
        { title: "Deployment (Docker, Gunicorn, AWS)", slug: "deployment", icon: "🚀", iconBgClassName: "bg-gray-100" },
      ],
    },
  ],
};