export const reactSyllabus = {
  title: "React",
  sections: [
    {
      title: "Basics",
      icon: "🧱",
      description: "Get started with React – learn components, JSX, props, state, and building your first interactive UI.",
      topics: [
        { title: "What is React?", slug: "what-is-react", icon: "⚛️", iconBgClassName: "bg-cyan-100" },
        { title: "JSX", slug: "jsx", icon: "📝", iconBgClassName: "bg-blue-100" },
        { title: "Components (Functional & Class)", slug: "components", icon: "🧩", iconBgClassName: "bg-purple-100" },
        { title: "Props", slug: "props", icon: "📤", iconBgClassName: "bg-green-100" },
        { title: "State (useState)", slug: "use-state", icon: "📊", iconBgClassName: "bg-yellow-100" },
        { title: "Event Handling", slug: "event-handling", icon: "🎯", iconBgClassName: "bg-orange-100" },
        { title: "Conditional Rendering", slug: "conditional-rendering", icon: "🔀", iconBgClassName: "bg-indigo-100" },
        { title: "Lists & Keys", slug: "lists-and-keys", icon: "📋", iconBgClassName: "bg-pink-100" },
        { title: "Forms & Controlled Components", slug: "forms", icon: "📝", iconBgClassName: "bg-teal-100" },
        { title: "Styling in React (CSS, Tailwind, CSS Modules)", slug: "styling", icon: "🎨", iconBgClassName: "bg-rose-100" },
      ],
    },
    {
      title: "Intermediate",
      icon: "⚡",
      description: "Master hooks, side effects, context, routing, and performance techniques.",
      topics: [
        { title: "useEffect", slug: "use-effect", icon: "🔄", iconBgClassName: "bg-blue-100" },
        { title: "useRef", slug: "use-ref", icon: "🏷️", iconBgClassName: "bg-gray-100" },
        { title: "useReducer", slug: "use-reducer", icon: "⚖️", iconBgClassName: "bg-red-100" },
        { title: "useCallback & useMemo", slug: "use-callback-memo", icon: "⚡", iconBgClassName: "bg-yellow-100" },
        { title: "Custom Hooks", slug: "custom-hooks", icon: "🪝", iconBgClassName: "bg-purple-100" },
        { title: "Context API", slug: "context-api", icon: "🌐", iconBgClassName: "bg-green-100" },
        { title: "React Router", slug: "react-router", icon: "🧭", iconBgClassName: "bg-orange-100" },
        { title: "Fetching Data (fetch, axios)", slug: "data-fetching", icon: "📡", iconBgClassName: "bg-teal-100" },
        { title: "Error Boundaries", slug: "error-boundaries", icon: "⚠️", iconBgClassName: "bg-red-100" },
        { title: "Portals", slug: "portals", icon: "🚪", iconBgClassName: "bg-indigo-100" },
        { title: "Higher-Order Components (HOCs)", slug: "hoc", icon: "🎭", iconBgClassName: "bg-pink-100" },
        { title: "Render Props", slug: "render-props", icon: "🎨", iconBgClassName: "bg-amber-100" },
      ],
    },
    {
      title: "Advanced",
      icon: "🚀",
      description: "Deep dive into performance, state management, testing, SSR, and production-ready patterns.",
      topics: [
        { title: "React.memo & PureComponent", slug: "react-memo", icon: "🧠", iconBgClassName: "bg-slate-100" },
        { title: "Code Splitting & Lazy Loading", slug: "code-splitting", icon: "✂️", iconBgClassName: "bg-cyan-100" },
        { title: "State Management (Redux, Zustand)", slug: "state-management", icon: "🏪", iconBgClassName: "bg-purple-100" },
        { title: "React Query / TanStack Query", slug: "react-query", icon: "📊", iconBgClassName: "bg-blue-100" },
        { title: "Server-Side Rendering (Next.js basics)", slug: "ssr", icon: "🖥️", iconBgClassName: "bg-gray-100" },
        { title: "Static Site Generation (Next.js)", slug: "ssg", icon: "📄", iconBgClassName: "bg-green-100" },
        { title: "Testing (Jest & React Testing Library)", slug: "testing", icon: "🧪", iconBgClassName: "bg-red-100" },
        { title: "Performance Optimization", slug: "performance", icon: "⚡", iconBgClassName: "bg-yellow-100" },
        { title: "Custom Renderers (React Native intro)", slug: "react-native", icon: "📱", iconBgClassName: "bg-indigo-100" },
        { title: "Design Patterns in React", slug: "design-patterns", icon: "🏗️", iconBgClassName: "bg-rose-100" },
        { title: "Security Best Practices (XSS, tokens)", slug: "security", icon: "🔐", iconBgClassName: "bg-orange-100" },
        { title: "Deployment & CI/CD", slug: "deployment", icon: "🚢", iconBgClassName: "bg-teal-100" },
      ],
    },
  ],
};