export const typescriptSyllabus = {
  title: "TypeScript",
  sections: [
    {
      title: "Basics",
      icon: "🟢",
      description: "Get started with TypeScript – understand what it is, why use it, and learn the core type system including basic types, functions, arrays, objects, and type aliases.",
      topics: [
        { title: "What is TypeScript?", slug: "what-is-typescript", icon: "📘", iconBgClassName: "bg-blue-100" },
        { title: "Setting Up Environment", slug: "setup", icon: "⚙️", iconBgClassName: "bg-gray-100" },
        { title: "Basic Types (number, string, boolean)", slug: "basic-types", icon: "🔢", iconBgClassName: "bg-green-100" },
        { title: "null, undefined, any, unknown, void, never", slug: "special-types", icon: "❓", iconBgClassName: "bg-yellow-100" },
        { title: "Type Inference & Annotations", slug: "type-inference", icon: "📝", iconBgClassName: "bg-purple-100" },
        { title: "Functions (Types, Optional, Default, Return)", slug: "functions", icon: "⚙️", iconBgClassName: "bg-pink-100" },
        { title: "Arrays & Tuples", slug: "arrays-tuples", icon: "🗂️", iconBgClassName: "bg-orange-100" },
        { title: "Objects", slug: "objects", icon: "📦", iconBgClassName: "bg-indigo-100" },
        { title: "Type Aliases", slug: "type-aliases", icon: "🏷️", iconBgClassName: "bg-cyan-100" },
      ],
    },
    {
      title: "Intermediate",
      icon: "🟡",
      description: "Deepen your TypeScript knowledge – interfaces, union/intersection types, generics basics, enums, type assertions, modules, classes, and working with JavaScript libraries.",
      topics: [
        { title: "Interfaces", slug: "interfaces", icon: "📄", iconBgClassName: "bg-blue-100" },
        { title: "Union & Intersection Types", slug: "union-intersection", icon: "🔀", iconBgClassName: "bg-green-100" },
        { title: "Literal Types", slug: "literal-types", icon: "📏", iconBgClassName: "bg-yellow-100" },
        { title: "Generics (Introduction)", slug: "generics-intro", icon: "🧬", iconBgClassName: "bg-purple-100" },
        { title: "Enums", slug: "enums", icon: "🔢", iconBgClassName: "bg-pink-100" },
        { title: "Type Assertions", slug: "type-assertions", icon: "🎯", iconBgClassName: "bg-orange-100" },
        { title: "Modules (import/export)", slug: "modules", icon: "📦", iconBgClassName: "bg-indigo-100" },
        { title: "Classes (Properties, Methods, Modifiers)", slug: "classes", icon: "🏛️", iconBgClassName: "bg-cyan-100" },
        { title: "Working with JS Libraries (DefinitelyTyped)", slug: "definitely-typed", icon: "🔌", iconBgClassName: "bg-red-100" },
      ],
    },
    {
      title: "Advanced",
      icon: "🔴",
      description: "Master advanced TypeScript patterns – advanced generics, utility types, conditional/mapped types, type narrowing, declaration files, decorators, compiler config, framework integration, and best practices.",
      topics: [
        { title: "Advanced Generics (Constraints, Defaults)", slug: "advanced-generics", icon: "🧬", iconBgClassName: "bg-blue-100" },
        { title: "Utility Types (Partial, Pick, Omit, etc.)", slug: "utility-types", icon: "🛠️", iconBgClassName: "bg-green-100" },
        { title: "Conditional Types", slug: "conditional-types", icon: "❓", iconBgClassName: "bg-yellow-100" },
        { title: "Mapped Types", slug: "mapped-types", icon: "🗺️", iconBgClassName: "bg-purple-100" },
        { title: "Type Narrowing (typeof, instanceof, Guards)", slug: "type-narrowing", icon: "🔍", iconBgClassName: "bg-pink-100" },
        { title: "Declaration Files (.d.ts)", slug: "declaration-files", icon: "📄", iconBgClassName: "bg-orange-100" },
        { title: "Decorators", slug: "decorators", icon: "🎨", iconBgClassName: "bg-indigo-100" },
        { title: "Compiler Configuration (tsconfig.json)", slug: "tsconfig", icon: "⚙️", iconBgClassName: "bg-gray-100" },
        { title: "TypeScript with React", slug: "typescript-react", icon: "⚛️", iconBgClassName: "bg-cyan-100" },
        { title: "TypeScript with Node.js", slug: "typescript-node", icon: "🟢", iconBgClassName: "bg-green-100" },
        { title: "Performance & Best Practices", slug: "best-practices", icon: "🚀", iconBgClassName: "bg-red-100" },
      ],
    },
  ],
};